### ISSUE TITLE
Error on deployment - openrct2-cli: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by solarsparq** [ich777/docker-openrct2-server#1]
Thank you for writing this Docker.  I configured it properly (per your documentation) & was greeted by this error.  Looks like some dependency is missing?  I saw a few other Docker servers running on the OpenRCT2 master server list & wanted to try running a few myself.  Let me know if you need anything from me.

---Starting...---
---OpenRCT2 version matches installed version---
---Preparing Server---
---Setting up config.ini---
---Applying patch for Debian Buster---
---Starting Server---
---No autosave found, loading save game: openrct2a.sv6---
/serverdata/serverfiles/openrct2-cli: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory
---Ensuring UID: 99 matches user---
usermod: no changes
---Ensuring GID: 100 matches user---
usermod: no changes
---Setting umask to 000---
---Checking for optional scripts---
---No optional script found, continuing---
---Taking ownership of data...---
---Starting...---
---OpenRCT2 version matches installed version---
---Preparing Server---
---Setting up config.ini---
---Applying patch for Debian Buster---
---Starting Server---
---No autosave found, loading save game: openrct2a.sv6---
/serverdata/serverfiles/openrct2-cli: error while loading shared libraries: libcrypto.so.3: cannot open shared object file: No such file or directory

**Comment by ich777** [comment]
Thank you for the Report! I will look into it ASAP amd report back.

**Comment by ich777** [comment]
@solarsparq please update the container, the issue should now be resolved.
I'll close this issue for now, please feel free to open the issue again if you are experiencing any further issues or create a new issue.

**Comment by solarsparq** [comment]
Thank you! .. from the Pink Sheep Club (a Minecraft guild).  Keep up the great work on Docker.  Your Vintage Story Docker was in the right place at the right time yesterday for me too.  OpenRCT2 is fantastic with OpenGL & unlimited FPS.  Now multi-player.. hats off to the open source community for not letting a classic fall.
![Openrct2 Screenshot 2022 11 18 - 08 12 01 85](https://user-images.githubusercontent.com/17531266/202724610-16e64811-0ad9-4adb-94ab-cf2a4261f885.png)
